name: ATHENA
main: io.github.thatsmusic99.athena.AthenaCore
version: 1.0-BETA-2
author: Thatsmusic99
api-version: 1.17
contributors: [oxolotel]

commands:
  athena:
    description: Core ATHENA command