name: ATHENA
main: io.github.thatsmusic99.athena.AthenaCore
version: ${project.version}
author: Thatsmusic99
api-version: 1.17
contributors: [oxolotel, YouHaveTrouble]
commands:
  athena:
    description: Core ATHENA command